"""Prints and saves a snapshot of headline project metrics.

Usage:
    python utils/project_stats.py

Writes the same numbers to docs/project_stats.md so they can be referenced from the README
or portfolio docs without re-running the script.
"""

import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd  # noqa: E402

from src.utils.db import get_engine  # noqa: E402

OUTPUT_PATH = "docs/project_stats.md"


def gather_stats() -> dict:
    engine = get_engine()

    total_customers = pd.read_sql("SELECT COUNT(*) n FROM raw_customers", engine).iloc[
        0
    ]["n"]

    churn_rate = pd.read_sql(
        "SELECT ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) "
        "AS pct FROM raw_customers",
        engine,
    ).iloc[0]["pct"]

    high_risk_count = pd.read_sql(
        "SELECT COUNT(*) n FROM churn_predictions WHERE risk_segment = 'High'", engine
    ).iloc[0]["n"]

    best_model = pd.read_sql(
        "SELECT model_name, model_version, auc_score, trained_at "
        "FROM model_registry WHERE is_active = TRUE LIMIT 1",
        engine,
    )

    total_predictions = pd.read_sql(
        "SELECT COUNT(*) n FROM churn_predictions", engine
    ).iloc[0]["n"]

    revenue_at_risk = pd.read_sql(
        "SELECT COALESCE(SUM(rc.monthly_charges), 0) AS total "
        "FROM churn_predictions cp JOIN raw_customers rc ON rc.customer_id = cp.customer_id "
        "WHERE cp.risk_segment IN ('High', 'Medium')",
        engine,
    ).iloc[0]["total"]

    return {
        "total_customers": int(total_customers),
        "churn_rate_pct": float(churn_rate),
        "high_risk_count": int(high_risk_count),
        "best_model_name": (
            best_model.iloc[0]["model_name"] if not best_model.empty else "N/A"
        ),
        "best_model_auc": (
            float(best_model.iloc[0]["auc_score"]) if not best_model.empty else None
        ),
        "total_predictions": int(total_predictions),
        "revenue_at_risk": float(revenue_at_risk),
        "last_trained_at": (
            best_model.iloc[0]["trained_at"] if not best_model.empty else None
        ),
    }


def render_report(stats: dict) -> str:
    trained_at_str = (
        stats["last_trained_at"].strftime("%Y-%m-%d %H:%M:%S")
        if stats["last_trained_at"] is not None
        else "N/A"
    )
    auc_str = (
        f"{stats['best_model_auc']:.4f}"
        if stats["best_model_auc"] is not None
        else "N/A"
    )

    lines = [
        "# Project Stats",
        "",
        "_Generated by `utils/project_stats.py` on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}._",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Total customers | {stats['total_customers']:,} |",
        f"| Churn rate | {stats['churn_rate_pct']:.2f}% |",
        f"| High risk customers | {stats['high_risk_count']:,} |",
        f"| Best model | {stats['best_model_name']} |",
        f"| Best model AUC | {auc_str} |",
        f"| Total predictions made | {stats['total_predictions']:,} |",
        f"| Revenue at risk (High+Medium) | ${stats['revenue_at_risk']:,.2f}/month |",
        f"| Last model training date | {trained_at_str} |",
        "",
    ]
    return "\n".join(lines)


def print_stats(stats: dict) -> None:
    trained_at_str = (
        stats["last_trained_at"].strftime("%Y-%m-%d %H:%M:%S")
        if stats["last_trained_at"] is not None
        else "N/A"
    )
    auc_str = (
        f"{stats['best_model_auc']:.4f}"
        if stats["best_model_auc"] is not None
        else "N/A"
    )

    print("=== Customer Churn Predictor — Project Stats ===")
    print(f"Total customers in database:  {stats['total_customers']:,}")
    print(f"Churn rate:                   {stats['churn_rate_pct']:.2f}%")
    print(f"High risk customer count:     {stats['high_risk_count']:,}")
    print(f"Best model:                   {stats['best_model_name']} (AUC={auc_str})")
    print(f"Total predictions made:       {stats['total_predictions']:,}")
    print(f"Revenue at risk (High+Medium):${stats['revenue_at_risk']:,.2f}/month")
    print(f"Last model training date:     {trained_at_str}")


def main() -> None:
    stats = gather_stats()
    print_stats(stats)

    report = render_report(stats)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\nSaved stats to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
